GET http://localhost:3000/quotes

###
GET http://localhost:3000/quotes/5e4a5ed651e87e8ba8033c4e

###
POST http://localhost:3000/quotes
Content-Type: application/json

{
    "title": "En mand bliver forvandlet til en måge.",
    "quoteText": "Mågen møder en blondine og siger jeg tror vi er tvillinger.",
    "author": "Jonas",
    "category": "5e4481bf0cad2f4b688ba5da"
}

###
PATCH  http://localhost:3000/quotes/5e4a5ed651e87e8ba8033c4e
Content-Type: application/json

{
    "title": "slepppp"
}


###
DELETE http://localhost:3000/quotes/5e3d4d5cc0eb73284d5c73f5

###
PATCH http://localhost:3000/quotes/
Content-Type: application/json

{
    "title": "New title"
}

###
GET http://localhost:3000/quotes/search/friend

// Categories

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "categoryName": "Love Quotes"
}

###

GET http://localhost:3000/categories
