GET http://localhost:3000/jokes

###
GET http://localhost:3000/jokes/5e3064da52ba2a245c94cd7e

###
POST http://localhost:3000/jokes
Content-Type: application/json

{
    "title": "En mand bliver forvandlet til en måge.",
    "jokeText": "Mågen møder en blondine og siger jeg tror vi er tvillinger."
}



### 
DELETE http://localhost:3000/jokes/5e31fca8942e036a94bb599f

###
PATCH http://localhost:3000/jokes/5e3042a148393319f96f4a5f
Content-Type: application/json

{
    "title": "Ny titel"
}

###
GET http://localhost:3000/jokes/search/

###
GET http://localhost:3000/jokes?page=1&limit=2

