GET http://localhost:3000/users/users

###
GET http://localhost:3000/users/

###
POST http://localhost:3000/users/user/create
Content-Type: application/json

{
    "name": "Jonas Voetmann",
    "email": "jonasv2711@gmail.com",
    "password": "hej123"
}

###
DELETE http://localhost:3000/users/5e3d4d5cc0eb73284d5c73f5
